// <auto-generated />
using System;
using AspNetBalanceSheet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetBalanceSheet.Migrations
{
    [DbContext(typeof(BalanceSheetContext))]
    [Migration("20240702042302_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AspNetBalanceSheet.Models.Balance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ID");

                    b.ToTable("Balances");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Account = "Cash",
                            Amount = 50.00m,
                            Category = "Food",
                            EntryType = "Expense"
                        },
                        new
                        {
                            ID = 2,
                            Account = "Bank",
                            Amount = 2000.00m,
                            Category = "Salary",
                            EntryType = "Income"
                        });
                });

            modelBuilder.Entity("AspNetBalanceSheet.Models.BalanceTransaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsFlip")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ID");

                    b.ToTable("BalanceTransactions");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Account = "Cash",
                            Amount = 50.00m,
                            Date = new DateTime(2024, 7, 2, 11, 23, 2, 593, DateTimeKind.Local).AddTicks(4384),
                            IsFlip = false,
                            TransactionType = "Expense"
                        },
                        new
                        {
                            ID = 2,
                            Account = "Bank",
                            Amount = 2000.00m,
                            Date = new DateTime(2024, 7, 2, 11, 23, 2, 593, DateTimeKind.Local).AddTicks(4397),
                            IsFlip = false,
                            TransactionType = "Income"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
